apiVersion: pksapi.io/v1beta1
kind: MetricSink
metadata:
  name: default-ns-sink
  namespace: default
spec:
  inputs:
  outputs:
  - type: influxdb
    urls: 
    - http://cluster-metric-sink-service.pks-system.svc.cluster.local
